---
- name: Configura Router FreeBSD
  hosts: bsd_router
  become: true

  roles:
    - freebsd_router

  tasks:
    - name: Importa task di tuning kernel
      ansible.builtin.import_tasks: roles/freebsd_router/tasks/tuning.yml

    - name: Importa task WireGuard VPN
      ansible.builtin.import_tasks: roles/freebsd_router/tasks/wireguard.yml

- name: Configura Suricata IDS
  hosts: bsd_router
  become: true
  tags: suricata

  handlers:
    - name: Restart suricata
      ansible.builtin.service:
        name: suricata
        state: restarted

  tasks:
    - name: Importa task Suricata
      ansible.builtin.import_tasks: roles/freebsd_router/tasks/suricata.yml
