---
- name: Configura Router FreeBSD
  hosts: bsd_router
  become: true

  roles:
    - freebsd_router
    - role: gaming
      tags: [gaming, never]
    - role: wireguard
      tags: [wireguard, never]

  tasks:
    - name: Importa task di tuning kernel
      ansible.builtin.import_tasks: roles/freebsd_router/tasks/tuning.yml
