---
- name: Reload pf
  ansible.builtin.command: /sbin/pfctl -f /etc/pf.conf
  changed_when: false

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart unbound
  ansible.builtin.service:
    name: unbound
    state: restarted

- name: Restart dhcpd
  ansible.builtin.service:
    name: isc-dhcpd
    state: restarted

- name: Restart suricata
  ansible.builtin.service:
    name: suricata
    state: restarted
